# Generated by Django 4.2.3 on 2023-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_cars_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column1", models.CharField(max_length=100)),
                ("column2", models.TextField()),
                ("column3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("column4", models.PositiveIntegerField()),
            ],
        ),
    ]
