# Generated by Django 4.2.3 on 2023-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_mytable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_model",
            field=models.CharField(max_length=200, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_submodel",
            field=models.CharField(max_length=200, verbose_name="Sub Model"),
        ),
        migrations.AlterField(
            model_name="car",
            name="maker",
            field=models.CharField(max_length=200, verbose_name="Maker"),
        ),
    ]
