# Generated by Django 4.2.3 on 2023-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_charger_delete_mytable_car_charger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charger",
            name="maker",
        ),
        migrations.RemoveField(
            model_name="charger",
            name="model",
        ),
        migrations.RemoveField(
            model_name="charger",
            name="type",
        ),
        migrations.AddField(
            model_name="charger",
            name="plug_type",
            field=models.CharField(default=1, max_length=200, verbose_name="Plug Type"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="charger",
            name="speed",
            field=models.CharField(max_length=200, verbose_name="Charging Speed"),
        ),
    ]
