# Generated by Django 4.2.3 on 2023-08-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_car_charger"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
    ]
