# Generated by Django 4.2.3 on 2023-08-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_delete_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maker", models.CharField(max_length=200, verbose_name="Maker")),
                ("car_model", models.CharField(max_length=200, verbose_name="Model")),
                (
                    "car_submodel",
                    models.CharField(max_length=200, verbose_name="Sub Model"),
                ),
                (
                    "charger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.charger"
                    ),
                ),
            ],
        ),
    ]
