# Generated by Django 4.2.3 on 2023-08-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="charger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.charger",
            ),
        ),
    ]
