# Generated by Django 4.2.3 on 2023-08-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Messege",
        ),
    ]
