# Generated by Django 4.2.3 on 2023-08-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charging_Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="address")),
                (
                    "charger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.charger",
                    ),
                ),
            ],
        ),
    ]
