# Generated by Django 4.2.3 on 2023-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_chargingstation_delete_charging_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingstation",
            name="description",
            field=models.CharField(default=2, max_length=200, verbose_name="address"),
            preserve_default=False,
        ),
    ]
