# Generated by Django 4.2.3 on 2023-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_alter_chargingstation_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingstation",
            name="description",
            field=models.CharField(
                max_length=200, null=True, verbose_name="description"
            ),
        ),
    ]
