# Generated by Django 4.2.3 on 2023-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_alter_chargingstation_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingstation",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default=("closed", "Closed"),
                max_length=10,
            ),
        ),
    ]
