# Generated by Django 4.2.3 on 2023-08-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_chargingstation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chargingstation",
            name="status",
        ),
    ]
