# Generated by Django 4.2.3 on 2023-08-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_remove_chargingstation_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="car_submodel",
            new_name="battery_pack_kwh",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="maker",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="charger",
            new_name="plug_type",
        ),
    ]
