# Generated by Django 4.2.3 on 2023-08-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_rename_car_submodel_car_battery_pack_kwh_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="plug_type",
        ),
    ]
