# Generated by Django 4.2.3 on 2023-08-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_car_plug_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=200, verbose_name="Maker")),
                ("car_model", models.CharField(max_length=200, verbose_name="Model")),
                (
                    "battery_pack_kwh",
                    models.CharField(max_length=200, verbose_name="Sub Model"),
                ),
                (
                    "plug_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.charger",
                    ),
                ),
            ],
        ),
    ]
