# Generated by Django 4.2.3 on 2023-08-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_cars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="battery_pack_kwh",
            field=models.CharField(max_length=200, verbose_name="battery_pack_kwh"),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_model",
            field=models.CharField(max_length=200, verbose_name="car_model"),
        ),
        migrations.DeleteModel(
            name="Cars",
        ),
    ]
