# Generated by Django 4.2.3 on 2023-08-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0028_alter_car_brand_alter_car_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="plug_type",
            field=models.CharField(
                default="", max_length=100, verbose_name="Plug Type"
            ),
        ),
    ]
