# Generated by Django 4.2.3 on 2023-08-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_alter_car_plug_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="plug_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.charger",
            ),
        ),
    ]
