# Generated by Django 4.2.3 on 2023-08-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_alter_car_plug_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="charging_station",
        ),
        migrations.AddField(
            model_name="profile",
            name="cars",
            field=models.ManyToManyField(blank=True, to="myapp.car"),
        ),
        migrations.AddField(
            model_name="profile",
            name="charging_stations",
            field=models.ManyToManyField(blank=True, to="myapp.chargingstation"),
        ),
        migrations.AddField(
            model_name="profile",
            name="max_walking_distance",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
