# Generated by Django 4.2.3 on 2023-08-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_banana"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banana",
        ),
    ]
