# Generated by Django 4.2.3 on 2023-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0037_chargingstation_station_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingstation",
            name="station_status",
            field=models.CharField(
                choices=[("Used", "Used"), ("Available", "Available"), ("Off", "Off")],
                default="Available",
                max_length=10,
                verbose_name="station status",
            ),
        ),
    ]
