# Generated by Django 4.2.3 on 2023-09-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0038_alter_chargingstation_station_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
        ),
    ]
