# Generated by Django 4.2.3 on 2023-10-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0045_remove_profile_user_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="Profile_user",
        ),
    ]
