# Generated by Django 4.2.3 on 2023-10-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0046_rename_user_profile_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="Profile_user",
            new_name="user",
        ),
    ]
