# Generated by Django 4.2.3 on 2023-10-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0047_rename_profile_user_profile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargingStations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="address")),
                (
                    "description",
                    models.CharField(
                        max_length=200, null=True, verbose_name="description"
                    ),
                ),
                (
                    "working_hours_start",
                    models.TimeField(null=True, verbose_name="working hours start"),
                ),
                (
                    "working_hours_finish",
                    models.TimeField(null=True, verbose_name="working hours finish"),
                ),
                (
                    "station_status",
                    models.CharField(
                        choices=[
                            ("Used", "Used"),
                            ("Available", "Available"),
                            ("Off", "Off"),
                        ],
                        default="Available",
                        max_length=10,
                        verbose_name="station status",
                    ),
                ),
                (
                    "charger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.charger",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
