# Generated by Django 4.2.3 on 2023-10-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0048_chargingstations"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChargingStations",
        ),
    ]
