# Generated by Django 4.2.3 on 2023-10-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0050_remove_profile_charging_stations_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="charging_stations",
            field=models.ManyToManyField(blank=True, to="myapp.chargingstation"),
        ),
    ]
