# Generated by Django 4.2.3 on 2023-11-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0051_profile_charging_stations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercars",
            name="car",
        ),
        migrations.AlterField(
            model_name="usercars",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
        migrations.AddField(
            model_name="usercars",
            name="car",
            field=models.ManyToManyField(to="myapp.car"),
        ),
    ]
