# Generated by Django 4.2.3 on 2023-11-02 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0052_remove_usercars_car_alter_usercars_user_usercars_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercars",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
