# Generated by Django 4.2.3 on 2023-11-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0053_alter_usercars_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercars",
            old_name="car",
            new_name="cars",
        ),
    ]
